apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-index
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Deployed via Jenkins on Kubernetes</title></head>
    <body>
      <h1>Welcome to Apache on Kubernetes!</h1>
      <p>This page was deployed automatically by Jenkins 🚀</p>
    </body>
    </html>
